# Write a program to input eight numbers from the user and display all the unique numbers (once).

x = set()
a = int(input("Enter the Number 1: "))
x.add(a)
b = int(input("Enter the Number 2: "))
x.add(b)
c = int(input("Enter the Number 3: "))
x.add(c)
d = int(input("Enter the Number 4: "))
x.add(d)
e = int(input("Enter the Number 5: "))
x.add(e)
f = int(input("Enter the Number 6: "))
x.add(f)
g = int(input("Enter the Number 7: "))
x.add(g)
h = int(input("Enter the Number 8: "))
x.add(h)
print(x)
print(type(x))